// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ceptctktcimsjlidfumu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlcHRjdGt0Y2ltc2psaWRmdW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzAwOTgsImV4cCI6MjA2NDUwNjA5OH0.MnsaGLDe0kTDLEQo4vWvw_HhHxFTBq_zhratf7LmEFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);